'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CP42QN5\SQLEXPRESS;Initial Catalog=SistemaCLR;Integrated Secu"& _ 
            "rity=True;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString1() As String
            Get
                Return CType(Me("SistemaCLRConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.64,49172;Initial Catalog=SistemaCLR;User ID=sa;Password=CAP"& _ 
            "UFE;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString() As String
            Get
                Return CType(Me("SistemaCLRConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CP42QN5\SQLEXPRESS;Initial Catalog=SistemaCLR;User ID=sa;Pass"& _ 
            "word=CAPUFE;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString2() As String
            Get
                Return CType(Me("SistemaCLRConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CP42QN5\SQLEXPRESS;Initial Catalog=SistemaCLR;User ID=sa;Encr"& _ 
            "ypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString3() As String
            Get
                Return CType(Me("SistemaCLRConnectionString3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CP42QN5\SQLEXPRESS;Initial Catalog=SistemaCLR;Integrated Secu"& _ 
            "rity=True;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString4() As String
            Get
                Return CType(Me("SistemaCLRConnectionString4"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.90,1433;Initial Catalog=SistemaCLR;User ID=usuario;Password"& _ 
            "=CAPUFE;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString5() As String
            Get
                Return CType(Me("SistemaCLRConnectionString5"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-N6FIP7JFSCI;Initial Catalog=SistemaCLR;User ID=usuario;Password=C"& _ 
            "APUFE;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString6() As String
            Get
                Return CType(Me("SistemaCLRConnectionString6"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.90,1433;Initial Catalog=SistemaCLR;User ID=usuario;Password"& _ 
            "=CAPUFE;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString7() As String
            Get
                Return CType(Me("SistemaCLRConnectionString7"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UV5M79I;Initial Catalog=SistemaCLR;Integrated Security=True;C"& _ 
            "onnect Timeout=30;Encrypt=False;TrustServerCertificate=True")>  _
        Public ReadOnly Property SistemaCLRConnectionString8() As String
            Get
                Return CType(Me("SistemaCLRConnectionString8"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SVL.My.MySettings
            Get
                Return Global.SVL.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
